'use client';
import Link from 'next/link';
import {useCallback,useEffect,useRef,useState} from 'react';
import QRScanner from '@/components/QRScanner';
import {Button,Field,Notice,PageHeading} from '@/components/tc/ui';
type Props={eventId:string;eventTitle:string;eventSlug:string;eventCity:string;eventVenue:string};
type Result={ok?:boolean;code?:string;error?:string;usedAtISO?:string;ticket?:{ticketTypeName:string;usedAtISO?:string}};
type Scan={id:string;ticketTypeName:string;usedAtISO:string;gate?:string;device?:string};
const labels:Record<string,string>={VALID:'Entrada aceptada',ALREADY_USED:'Esta entrada ya ingresó',INVALID_QR:'QR inválido',WRONG_EVENT:'Corresponde a otro evento',UNKNOWN_TICKET:'Entrada no encontrada',CANCELLED:'Entrada cancelada o no habilitada',ACCESS_CLOSED:'Acceso cerrado o puerta no habilitada',NOT_AUTHORIZED:'No tienes acceso a este evento',UNAUTHENTICATED:'Inicia sesión nuevamente',NETWORK:'Sin conexión',SERVER:'No pudimos confirmar el ingreso'};
export default function ScannerUI({eventId,eventTitle,eventCity,eventVenue}:Props){
 const [online,setOnline]=useState(true),[busy,setBusy]=useState(false),[result,setResult]=useState<Result|null>(null),[manual,setManual]=useState(''),[lookup,setLookup]=useState<{id:string;ticket_type_name:string;status:string}|null>(null),[gate,setGate]=useState(''),[device,setDevice]=useState(''),[gates,setGates]=useState<string[]>([]),[scans,setScans]=useState<Scan[]>([]),[counts,setCounts]=useState({pending:0,used:0}),[error,setError]=useState('');
 const metricsInFlight=useRef(false),inFlight=useRef(false),resultHeading=useRef<HTMLHeadingElement>(null);
 const refresh=useCallback(async()=>{if(metricsInFlight.current||document.hidden||!navigator.onLine)return;metricsInFlight.current=true;try{const [a,b]=await Promise.all([fetch(`/api/scanner/event-stats?eventId=${eventId}`),fetch(`/api/scanner/event-checkins?eventId=${eventId}`)]);if(!a.ok||!b.ok)throw Error('No se pudo actualizar el acceso. Revisa tu sesión y conexión.');const stats=await a.json(),recent=await b.json();setCounts(stats.totals||stats.stats?.totals||{pending:0,used:0});setScans(recent.checkins||recent.items||recent);setError('');}catch(e){setError(e instanceof Error?e.message:'No se pudo actualizar.');}finally{metricsInFlight.current=false;}},[eventId]);
 useEffect(()=>{const update=()=>setOnline(navigator.onLine);update();window.addEventListener('online',update);window.addEventListener('offline',update);void refresh();const timer=setInterval(()=>void refresh(),15000);fetch(`/api/scanner/config?eventId=${eventId}`).then(r=>r.json()).then(c=>{setGates(c.gates||[]);setGate(c.gates?.[0]||'');}).catch(()=>{});return()=>{clearInterval(timer);window.removeEventListener('online',update);window.removeEventListener('offline',update);};},[eventId,refresh]);
 async function scan(text:string,manualMode=false){if(inFlight.current||result||!online)return;inFlight.current=true;setBusy(true);try{const r=await fetch('/api/scanner/checkin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({eventId,...(manualMode?{ticketId:text}:{qrText:text}),gate,device})});const d=await r.json();setResult({...d,code:d.code||(r.status>=500?'SERVER':'NOT_AUTHORIZED')});void refresh();}catch{setResult({code:'NETWORK',error:'No confirmes el ingreso sin respuesta del servidor. Revisa la conexión y consulta nuevamente.'});}finally{setBusy(false);inFlight.current=false;setTimeout(()=>resultHeading.current?.focus(),0);}}
 async function find(){setError('');setLookup(null);try{const r=await fetch(`/api/scanner/lookup?eventId=${eventId}&ticketId=${encodeURIComponent(manual)}`),d=await r.json();if(!r.ok)throw Error(d.error);setLookup(d);}catch(e){setError(e instanceof Error?e.message:'No se pudo consultar.');}}
 return <div className="tc"><main className="container page stack scanner-page"><Link href="/scanner">← Eventos asignados</Link><PageHeading eyebrow="Acceso / Scanner" title={eventTitle}>{eventVenue} · {eventCity}</PageHeading><Notice>{online?'En línea · cada ingreso se verifica en el servidor.':'Sin conexión. El scanner no permite validar entradas offline.'}</Notice><div className="row"><span className="mono">{counts.used} ingresaron</span><span>{counts.pending} pendientes</span></div><div className="ai-fields"><Field label="Puerta"><select value={gate} onChange={e=>setGate(e.target.value)}>{gates.length?gates.map(g=><option key={g}>{g}</option>):<option value="">Acceso general</option>}</select></Field><Field label="Etiqueta de este dispositivo (opcional)"><input maxLength={60} value={device} onChange={e=>setDevice(e.target.value)} placeholder="Equipo 1"/></Field></div>
 {result&&<section className={`scanner-result ${result.ok?'accepted':'rejected'}`} role="status"><h2 ref={resultHeading} tabIndex={-1}>{labels[result.code||'SERVER']||'Ingreso no confirmado'}</h2><p>{result.ticket?.ticketTypeName||result.error}</p>{(result.usedAtISO||result.ticket?.usedAtISO)&&<p>{new Date(result.usedAtISO||result.ticket!.usedAtISO!).toLocaleString('es-CL')}</p>}<Button onClick={()=>{setResult(null);setLookup(null);}}>Siguiente entrada</Button></section>}
 {busy&&<Notice>Verificando ingreso…</Notice>}<QRScanner paused={busy||!!result||!online} onResult={text=>void scan(text)}/><section className="panel stack"><h2>Consulta manual</h2><Field label="Código completo de entrada" hint="Consulta exacta dentro de este evento. No busca nombres ni correos."><input value={manual} maxLength={200} onChange={e=>{setManual(e.target.value);setLookup(null);}}/></Field><Button variant="secondary" disabled={!manual||busy||!online} onClick={()=>void find()}>Buscar entrada</Button>{lookup&&<div className="stack-sm"><p>{lookup.ticket_type_name} · {lookup.status}</p><Button disabled={lookup.status!=='VALID'||busy||!!result||!online} onClick={()=>void scan(lookup.id,true)}>Confirmar ingreso manual</Button></div>}</section>{error&&<Notice error>{error}</Notice>}<section className="stack"><h2>Ingresos recientes</h2>{scans.map(s=><div className="history-row" key={s.id}><span>{s.ticketTypeName}<small className="hint"> {s.gate||'Acceso general'} {s.device}</small></span><time>{new Date(s.usedAtISO).toLocaleTimeString('es-CL')}</time></div>)}{!scans.length&&<p>Aún no hay ingresos.</p>}</section></main></div>;
}
