import fs from 'node:fs';
import {spawn} from 'node:child_process';
import dotenv from 'dotenv';
import sharp from 'sharp';
import {localDatabase} from '../tests/local-postgres.mjs';
import {loadSource} from '../tests/load-source.mjs';
const env={...process.env,NODE_ENV:'development',NEXT_TELEMETRY_DISABLED:'1',TICKETCHILE_BUILD_DIR:'.next-m5-qa'};
for(const name of ['.env','.env.local','.env.development','.env.development.local','.env.production','.env.production.local'])if(fs.existsSync(name))for(const key of Object.keys(dotenv.parse(fs.readFileSync(name))))env[key]='';
for(const key of Object.keys(env))if(/^(MEDIA_|AWS_|VERCEL_|AI_|OPENAI_|STRIPE_|FLOW_|WEBPAY_|FINTOC_|RESEND_|MAIL_|CHECKOUT_|FROM_EMAIL$|GOOGLE_|AUTH_|SECURITY_|NEXTAUTH_|TRANSFER_|ORGANIZER_|ADMIN_BOOTSTRAP_|APP_|NEXT_PUBLIC_|SUPPORT_)/.test(key))env[key]='';
const db=await localDatabase(),url=`postgresql://ticket_local@127.0.0.1:55439/${db.database}`;
for(const key of ['TICKETCHILE_DB_POSTGRES_URL','TICKETCHILE_DB_POSTGRES_URL_NON_POOLING','POSTGRES_URL','POSTGRES_URL_NON_POOLING','POSTGRES_PRISMA_URL','DATABASE_URL'])env[key]=url;
Object.assign(env,{DATABASE_SSL:'false',APP_ENVIRONMENT:'development',WALLET_RESOURCE_ENVIRONMENT:'development',SECURITY_DATA_KEY:Buffer.alloc(32,12).toString('base64'),NEXTAUTH_SECRET:'m12-synthetic-session-secret',NEXTAUTH_URL:'http://localhost:3005',NEXTAUTH_URL_INTERNAL:'http://localhost:3005',APP_BASE_URL:'http://localhost:3005',TICKETCHILE_QR_SECRET:'m12-synthetic-qr-secret',STRIPE_SECRET_KEY:'sk_test_disabled',RESEND_API_KEY:'re_disabled',MEDIA_PROVIDER:'local'});
process.env.SECURITY_DATA_KEY=env.SECURITY_DATA_KEY;
await db.pool.query("INSERT INTO organizer_users(id,username,display_name,password_hash,verified,approved) VALUES('m12-organizer','m12-organizer','Producciones Cordillera','disabled',true,true)");
await db.pool.query("INSERT INTO admin_users(id,username,display_name,password_hash,role) VALUES('m12-admin','m12-admin','Review QA','disabled','SUPERADMIN')");
await db.pool.query("INSERT INTO identity_mfa(kind,principal_id,enabled) VALUES('ADMIN','m12-admin',true),('ORGANIZER','m12-organizer',true)");
const identity=loadSource('lib/security/identity.server.ts',{'@/lib/db':db});
const organizer=await identity.createSession(await identity.principal('ORGANIZER','m12-organizer'),true);
const admin=await identity.createSession(await identity.principal('ADMIN','m12-admin'),true);
fs.mkdirSync('.local',{recursive:true});
await sharp('public/events/noche-rock.jpg').resize({width:2200,withoutEnlargement:true}).png().toFile('.local/m12-input.png');
await sharp('public/events/sunset-party.jpg').resize({width:1800,withoutEnlargement:true}).png().toFile('.local/m12-replacement.png');
fs.writeFileSync('.local/m12-invalid.png','Not an image');
fs.writeFileSync('.local/m12-preview.json',JSON.stringify({database:db.database,organizer,admin}));await db.pool.end();
console.log('M12 synthetic preview on loopback:3005. Local media; external providers disabled.');
const child=spawn(process.execPath,['node_modules/next/dist/bin/next','dev','--hostname','127.0.0.1','--port','3005'],{env,stdio:'inherit',windowsHide:true});
process.on('SIGINT',()=>child.kill());process.on('SIGTERM',()=>child.kill());child.on('exit',code=>process.exit(code??0));
