import {before,after,test} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {localDatabase} from './local-postgres.mjs';
import {loadSource} from './load-source.mjs';
let db,actor,owner,foreign,service,ops,identity,model;
const key=process.env.SECURITY_DATA_KEY;
const overrides=()=>({'@/lib/db':db,'./http.server':{cookieIdentity:async()=>actor?.kind==='ORGANIZER'?actor:null},'./current.server':{buyerPrincipal:async()=>actor?.kind==='BUYER'?actor:null}});
const load=file=>loadSource(file,overrides());
async function buyer(role,eventIds,capabilities){const id=randomUUID();await db.pool.query("INSERT INTO usuarios(id,email,email_verified_at) VALUES($1,$2,now())",[id,`${id}@m6.test`]);await db.pool.query('INSERT INTO organizer_staff(id,organizer_id,buyer_id,role,capabilities,event_ids) VALUES($1,$2,$3,$4,COALESCE($5,staff_role_capabilities($4)),$6)',[randomUUID(),owner.id,id,role,capabilities||null,eventIds]);return identity.principal('BUYER',id);}
async function draft(){actor=owner;return (await service.createEvent(owner.id)).id;}
async function complete(id){const e=await service.readEvent(id,'event.edit');const media=randomUUID();await db.pool.query("INSERT INTO media_objects(id,organizer_id,event_id,object_key,content_type,bytes) VALUES($1,$2,$3,$4,'image/webp',100)",[media,owner.id,id,`${media}.webp`]);const d={...model.emptyDraft,title:'Evento de prueba',description:'Una descripción completa para revisar este evento.',category_slug:'conciertos',date_iso:new Date(Date.now()+86400000*20).toISOString(),end_at:new Date(Date.now()+86400000*20+7200000).toISOString(),city:'Santiago',region:'Metropolitana',venue:'Recinto confirmado',address:'Dirección confirmada',capacity:100,age_policy:'Adultos',access_info:'Acceso principal',image:`/api/media/${media}`,tiers:[{id:'general',name:'Acceso general',description:'Primer piso',price_clp:12000,capacity:80,max_per_order:4,sales_start:null,sales_end:null,visible:true,active:true},{id:'preferente',name:'Balcón',description:'Segundo piso',price_clp:20000,capacity:20,max_per_order:2,sales_start:null,sales_end:null,visible:true,active:true}]};await service.saveEvent(id,e.revision,d);return d;}
async function publish(id){let e=await service.readEvent(id);await service.transitionEvent(id,e.revision,'IN_REVIEW','IN_REVIEW');e=await service.readEvent(id);await service.transitionEvent(id,e.revision,'PUBLISHED','PUBLISHED');}
before(async()=>{process.env.SECURITY_DATA_KEY=Buffer.alloc(32,66).toString('base64');db=await localDatabase();identity=load('lib/security/identity.server.ts');for(const id of ['m6-owner','m6-foreign'])await db.pool.query("INSERT INTO organizer_users(id,username,display_name,password_hash,verified,approved) VALUES($1,$1,$1,'disabled',true,true)",[id]);owner=await identity.principal('ORGANIZER','m6-owner');foreign=await identity.principal('ORGANIZER','m6-foreign');actor=owner;service=load('lib/organizer/events.server.ts');ops=load('lib/organizer/operations.server.ts');model=load('lib/organizer/model.ts');});
after(async()=>{await db?.pool.end();if(key===undefined)delete process.env.SECURITY_DATA_KEY;else process.env.SECURITY_DATA_KEY=key;});
test('creation is private DRAFT with audit; cross-tenant IDs never grant access',async()=>{const id=await draft();const e=await service.readEvent(id);assert.equal(e.lifecycle,'DRAFT');assert.equal(e.date_iso,null);assert.equal(e.revision,1);assert.equal((await load('lib/events.server.ts').getEventByIdDb(id)),undefined);actor=foreign;for(const fn of [()=>service.readEvent(id),()=>service.saveEvent(id,1,model.emptyDraft),()=>service.transitionEvent(id,1,'IN_REVIEW','IN_REVIEW'),()=>service.createEvent(owner.id)])await assert.rejects(fn);assert.equal((await service.organizerEvents()).events.length,0);assert.equal((await db.pool.query("SELECT count(*)::int n FROM security_audit WHERE event_id=$1 AND action='event.created'",[id])).rows[0].n,1);});
test('draft save is revision-safe and concurrent autosaves cannot overwrite one another',async()=>{const id=await draft(),d=await complete(id),e=await service.readEvent(id);const results=await Promise.allSettled([service.saveEvent(id,e.revision,{...d,title:'Version A'}),service.saveEvent(id,e.revision,{...d,title:'Version B'})]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(results.find(r=>r.status==='rejected').reason.code,'REVISION_CONFLICT');assert.equal((await service.readEvent(id)).revision,e.revision+1);});
test('server validates numbers, sum capacity, windows, timezone, tier IDs and media ownership',async()=>{const id=await draft(),d=await complete(id),e=await service.readEvent(id);for(const bad of [{capacity:99},{capacity:-1},{timezone:'not/a-zone'},{image:'data:image/png;base64,AA=='},{tiers:[{...d.tiers[0],price_clp:-1}]},{tiers:[{...d.tiers[0],max_per_order:11}]},{tiers:[{...d.tiers[0],sales_start:d.end_at}]},{tiers:[d.tiers[0],d.tiers[0]]}])await assert.rejects(service.saveEvent(id,e.revision,{...d,...bad}));const media=randomUUID();await db.pool.query("INSERT INTO media_objects(id,organizer_id,object_key,content_type,bytes) VALUES($1,$2,$3,'image/webp',100)",[media,foreign.id,`${media}.webp`]);await assert.rejects(service.saveEvent(id,e.revision,{...d,image:`/api/media/${media}`}));assert.equal((await service.readEvent(id)).revision,e.revision);});
test('lifecycle requires checklist, ordered transitions, current revision and explicit owner confirmation',async()=>{const id=await draft();await assert.rejects(service.transitionEvent(id,1,'IN_REVIEW','IN_REVIEW'),{code:'PUBLISH_CHECKLIST'});const d=await complete(id);await assert.rejects(service.transitionEvent(id,2,'PUBLISHED','PUBLISHED'));await service.transitionEvent(id,2,'IN_REVIEW','IN_REVIEW');await assert.rejects(service.transitionEvent(id,3,'PUBLISHED',''));await service.saveEvent(id,3,d);assert.equal((await service.readEvent(id)).lifecycle,'DRAFT');await publish(id);const e=await service.readEvent(id);assert.ok(await load('lib/events.server.ts').getEventByIdDb(id));await assert.rejects(service.transitionEvent(id,e.revision,'ENDED','ENDED'));await assert.rejects(db.pool.query('UPDATE events SET is_published=false WHERE id=$1',[id]),{code:'23514'});});
test('role matrix and event grants constrain panel, finance, attendees, access, publication and staff',async()=>{const id=await draft();await complete(id);const other=await draft();for(const [role,allow,deny] of [['ORGANIZER_MANAGER',['event.read','event.edit','attendees.read','scanner.read'],['finance.read','staff.manage']],['ORGANIZER_DOOR',['scanner.read'],['event.edit','attendees.read','finance.read','staff.manage']],['ORGANIZER_FINANCE',['finance.read'],['event.edit','attendees.read','scanner.read','staff.manage']],['ORGANIZER_SUPPORT',['attendees.read'],['event.edit','finance.read','scanner.read','staff.manage']]]){actor=await buyer(role,[id]);for(const c of allow)assert.ok(await service.readEvent(id,c));for(const c of deny)await assert.rejects(service.readEvent(id,c),{status:404});await assert.rejects(service.readEvent(other),{status:404});assert.deepEqual((await service.organizerEvents()).events.map(e=>e.id),[id]);await assert.rejects(service.createEvent(owner.id));await assert.rejects(service.transitionEvent(id,2,'IN_REVIEW','IN_REVIEW'));if(role!=='ORGANIZER_FINANCE')await assert.rejects(ops.sales(id));if(role==='ORGANIZER_DOOR')await assert.rejects(ops.attendees(id));await assert.rejects(ops.staffForEvent(id));}actor=owner;assert.ok(await ops.staffForEvent(id));});
test('revoked grants and disabled tenant are denied without trusting client state',async()=>{const id=await draft();actor=await buyer('ORGANIZER_MANAGER',[id]);assert.ok(await service.readEvent(id));await db.pool.query('UPDATE organizer_staff SET revoked_at=now() WHERE buyer_id=$1',[actor.id]);await assert.rejects(service.readEvent(id));actor=owner;await db.pool.query("UPDATE identity_accounts SET disabled=true WHERE kind='ORGANIZER' AND id=$1",[owner.id]);await assert.rejects(service.readEvent(id));await db.pool.query("UPDATE identity_accounts SET disabled=false WHERE kind='ORGANIZER' AND id=$1",[owner.id]);owner=await identity.principal('ORGANIZER',owner.id);actor=owner;});
test('price edits preserve held prices; sold price edits require confirmation and stock protects committed units',async()=>{const id=await draft(),d=await complete(id);await publish(id);const hold=(await load('lib/hold.pg.server.ts').createHoldPgServer({eventId:id,ownerEmail:'local@m6.test',requested:[{ticketTypeId:'general',qty:2}]})).hold;await db.pool.query("UPDATE ticket_types SET sold=1 WHERE event_id=$1 AND id='general'",[id]);let e=await service.readEvent(id);const changed={...d,tiers:d.tiers.map(t=>({...t,price_clp:t.price_clp+1000}))};await assert.rejects(service.saveEvent(id,e.revision,changed),{code:'PRICE_CONFIRMATION'});await service.saveEvent(id,e.revision,changed,true);assert.equal((await db.pool.query('SELECT unit_price_clp FROM hold_items WHERE hold_id=$1',[hold.id])).rows[0].unit_price_clp,12000);e=await service.readEvent(id);await assert.rejects(service.saveEvent(id,e.revision,{...changed,tiers:changed.tiers.map(t=>({...t,capacity:1}))},true));await assert.rejects(service.saveEvent(id,e.revision,{...changed,address:'New address'},true),{code:'CRITICAL_EDIT'});});
test('inactive/private/future/closed tiers cannot reserve; pause hides discovery and rejects new holds',async()=>{const id=await draft(),d=await complete(id);await publish(id);const holds=load('lib/hold.pg.server.ts');for(const changes of [{active:false},{visible:false},{sales_start:new Date(Date.now()+3600000).toISOString()},{sales_end:new Date(Date.now()-3600000).toISOString()}]){const e=await service.readEvent(id);await service.saveEvent(id,e.revision,{...d,tiers:[{...d.tiers[0],...changes},d.tiers[1]]});await assert.rejects(holds.createHoldPgServer({eventId:id,ownerEmail:'local@m6.test',requested:[{ticketTypeId:'general',qty:1}]}));}const e=await service.readEvent(id);await service.transitionEvent(id,e.revision,'PAUSED','PAUSED');assert.equal(await load('lib/events.server.ts').getEventByIdDb(id),undefined);await assert.rejects(holds.createHoldPgServer({eventId:id,ownerEmail:'local@m6.test',requested:[{ticketTypeId:'preferente',qty:1}]}));});
test('cancellation releases holds once, invalidates unused tickets and records operational review without refunds',async()=>{const id=await draft();await complete(id);await publish(id);const hold=(await load('lib/hold.pg.server.ts').createHoldPgServer({eventId:id,ownerEmail:'local@m6.test',requested:[{ticketTypeId:'general',qty:2}]})).hold;await db.pool.query("INSERT INTO orders(id,hold_id,event_id,event_title,buyer_name,buyer_email,owner_email) VALUES($1,$2,$3,'Event','Person','local@m6.test','local@m6.test')",[id,hold.id,id]);await db.pool.query("INSERT INTO tickets(id,order_id,event_id,ticket_type_id,ticket_type_name,buyer_email,owner_email,status) VALUES($1,$2,$2,'general','General','local@m6.test','local@m6.test','VALID')",[`t-${id}`,id]);const e=await service.readEvent(id);await assert.rejects(service.transitionEvent(id,e.revision,'CANCELLED','CANCELLED'));await service.transitionEvent(id,e.revision,'CANCELLED',`CANCELAR ${id}`);assert.equal((await service.readEvent(id)).cancellation_followup,'REVIEW_REQUIRED');assert.equal((await db.pool.query('SELECT status FROM tickets WHERE id=$1',[`t-${id}`])).rows[0].status,'CANCELLED');assert.equal((await db.pool.query("SELECT held FROM ticket_types WHERE event_id=$1 AND id='general'",[id])).rows[0].held,0);await assert.rejects(service.saveEvent(id,e.revision+1,model.emptyDraft),{code:'EVENT_CLOSED'});assert.equal((await db.pool.query("SELECT count(*)::int n FROM security_audit WHERE event_id=$1 AND action='event.cancelled'",[id])).rows[0].n,1);});
test('AI unavailable endpoint never edits or publishes and enforces event capability first',async()=>{const id=await draft();await assert.rejects(ops.organizerProposal(id,'Create a wonderful concert'),{code:'AI_UNAVAILABLE'});assert.equal((await service.readEvent(id)).revision,1);actor=foreign;await assert.rejects(ops.organizerProposal(id,'Create a wonderful concert'),{status:404});});
test('local proposal is explicitly labeled, extracts only supplied facts and never mutates lifecycle',async()=>{
 const id=await draft(),previous=process.env.ORGANIZER_AI_ADAPTER;process.env.ORGANIZER_AI_ADAPTER='local';
 try{const proposal=await ops.organizerProposal(id,'Concierto "Nombre confirmado" en Santiago para 800 personas. General $15.000, VIP $30.000');assert.equal(proposal.source,'LOCAL_RULES');assert.equal(proposal.patch.title,'Nombre confirmado');assert.equal(proposal.patch.capacity,800);assert.equal(proposal.patch.tiers[0].price_clp,15000);assert.ok(proposal.patch.tiers.every(t=>!t.active&&t.capacity===0));for(const k of ['lifecycle','address','date_iso','age_policy'])assert.ok(!Object.hasOwn(proposal.patch,k));assert.equal((await service.readEvent(id)).revision,1);
 const production=process.env.NODE_ENV;process.env.NODE_ENV='production';try{await assert.rejects(ops.organizerProposal(id,'Concierto sin detalles'),{code:'AI_UNAVAILABLE'});}finally{if(production===undefined)delete process.env.NODE_ENV;else process.env.NODE_ENV=production;}
 }finally{if(previous===undefined)delete process.env.ORGANIZER_AI_ADAPTER;else process.env.ORGANIZER_AI_ADAPTER=previous;}
});
test('authorized preview never serializes base64; legacy media remains private and intact after an edit',async()=>{
 const id=await draft(),d=await complete(id),sharp=(await import('sharp')).default;
 const raw='data:image/png;base64,'+(await sharp({create:{width:12,height:12,channels:3,background:'red'}}).png().toBuffer()).toString('base64');await db.pool.query('UPDATE events SET image=$2 WHERE id=$1',[id,raw]);
 const e=await service.readEvent(id);assert.match(e.image,/^\/api\/event-preview-media\//);assert.ok(!JSON.stringify(e).includes('base64'));
 await service.saveEvent(id,e.revision,{...d,image:e.image,title:'Legacy maintained'});assert.equal((await db.pool.query('SELECT image FROM events WHERE id=$1',[id])).rows[0].image,raw);
 const route=load('app/api/event-preview-media/[id]/[slot]/route.ts'),ctx={params:Promise.resolve({id,slot:'poster'})};assert.equal((await route.GET(new Request('http://local'),ctx)).status,200);actor=foreign;assert.equal((await route.GET(new Request('http://local'),ctx)).status,404);
});
test('new event HTTP mutations reject anonymous, cross-origin, oversized and stale writes',async()=>{
 const id=await draft(),route=load('app/api/organizer/events/[id]/route.ts'),ctx={params:Promise.resolve({id})};
 const req=(origin,body)=>new Request(`https://local/api/organizer/events/${id}`,{method:'PATCH',headers:{origin,'Content-Type':'application/json'},body:JSON.stringify(body)});
 assert.equal((await route.PATCH(req('https://foreign',{draft:model.emptyDraft,revision:1}),ctx)).status,403);
 assert.equal((await route.PATCH(req('https://local',{draft:model.emptyDraft,revision:99}),ctx)).status,409);
 assert.equal((await route.PATCH(req('https://local',{data:'x'.repeat(132000)}),ctx)).status,413);
 actor=null;assert.equal((await route.GET(new Request('https://local'),ctx)).status,401);assert.equal((await route.PATCH(req('https://local',{draft:model.emptyDraft,revision:1}),ctx)).status,401);
});
test('attendees and financial aggregations use this event, current scope and historical prices',async()=>{
 const id=await draft();await complete(id);await publish(id);
 const hold=(await load('lib/hold.pg.server.ts').createHoldPgServer({eventId:id,ownerEmail:'buyer@m6.test',requested:[{ticketTypeId:'general',qty:1}]})).hold;
 await db.pool.query("INSERT INTO payments(id,hold_id,event_id,event_title,provider,provider_ref,buyer_name,buyer_email,owner_email,amount_clp,currency,status,creation_state) VALUES($1,$2,$3,'Event','stripe',$1,'Buyer name','contact@m6.test','buyer@m6.test',12000,'CLP','PENDING','READY')",[id,hold.id,id]);
 const finalizer=load('lib/payments/finalize.server.ts');await finalizer.recordVerifiedPayment({paymentId:id,provider:'stripe',reference:id,holdId:hold.id,amount:12000,currency:'CLP',status:'PAID',observationKey:randomUUID()});await finalizer.finalizePayment(id);
 const manager=await buyer('ORGANIZER_SUPPORT',[id]);actor=manager;const a=await ops.attendees(id,'contact@');assert.equal(a.total,1);assert.equal(a.rows[0].owner_email,'buyer@m6.test');assert.ok(!Object.hasOwn(a.rows[0],'amount_clp'));await assert.rejects(ops.sales(id));
 actor=owner;const e=await service.readEvent(id);await service.saveEvent(id,e.revision,{...e,tiers:e.tiers.map(t=>({...t,price_clp:t.price_clp+5000}))},true);
 const data=await ops.sales(id);assert.equal(data.summary.gross,'12000');assert.equal(data.tiers[0].gross,'12000');assert.equal(data.summary.orders,1);actor=foreign;await assert.rejects(ops.attendees(id));await assert.rejects(ops.sales(id));
});
test('pause preserves reserved fulfillment; cancellation routes late paid evidence to review without issuing',async()=>{
 for(const target of ['PAUSED','CANCELLED']){const id=await draft();await complete(id);await publish(id);const hold=(await load('lib/hold.pg.server.ts').createHoldPgServer({eventId:id,ownerEmail:`${id}@m6.test`,requested:[{ticketTypeId:'general',qty:1}]})).hold;
 await db.pool.query("INSERT INTO payments(id,hold_id,event_id,event_title,provider,provider_ref,buyer_name,buyer_email,owner_email,amount_clp,currency,status,creation_state) VALUES($1,$2,$3,'Event','stripe',$1,'Buyer name',$4,$4,12000,'CLP','PENDING','READY')",[id,hold.id,id,`${id}@m6.test`]);
 const e=await service.readEvent(id);await service.transitionEvent(id,e.revision,target,target==='CANCELLED'?`CANCELAR ${id}`:target);
 const f=load('lib/payments/finalize.server.ts');await f.recordVerifiedPayment({paymentId:id,provider:'stripe',reference:id,holdId:hold.id,amount:12000,currency:'CLP',status:'PAID',observationKey:randomUUID()});assert.equal((await f.finalizePayment(id)).status,target==='PAUSED'?'ISSUED':'REVIEW');assert.equal((await db.pool.query('SELECT count(*)::int n FROM tickets WHERE event_id=$1',[id])).rows[0].n,target==='PAUSED'?1:0);
 }
});
test('ending an elapsed event closes reservations and scanner while preserving ticket history',async()=>{
 const id=await draft();await complete(id);await publish(id);
 const hold=(await load('lib/hold.pg.server.ts').createHoldPgServer({eventId:id,ownerEmail:`${id}@m6.test`,requested:[{ticketTypeId:'general',qty:1}]})).hold;
 await db.pool.query("INSERT INTO orders(id,hold_id,event_id,event_title,buyer_name,buyer_email,owner_email) VALUES($1,$2,$1,'Event','Buyer','buyer@m6.test','buyer@m6.test')",[id,hold.id]);
 await db.pool.query("INSERT INTO tickets(id,order_id,event_id,ticket_type_id,ticket_type_name,buyer_email,owner_email,status) VALUES($1,$1,$1,'general','General','buyer@m6.test','buyer@m6.test','VALID')",[id]);
 await db.pool.query("UPDATE events SET date_iso=now()-interval '2 hours',end_at=now()-interval '1 hour' WHERE id=$1",[id]);
 const e=await service.readEvent(id);await service.transitionEvent(id,e.revision,'ENDED','ENDED');assert.equal((await db.pool.query('SELECT status FROM holds WHERE id=$1',[hold.id])).rows[0].status,'EXPIRED');
 const route=load('app/api/scanner/checkin/route.ts');const response=await route.POST(new Request('https://local/api/scanner/checkin',{method:'POST',headers:{origin:'https://local','Content-Type':'application/json'},body:JSON.stringify({eventId:id,ticketId:id})}));assert.equal(response.status,409);
 assert.equal((await db.pool.query('SELECT status FROM tickets WHERE id=$1',[id])).rows[0].status,'VALID');await assert.rejects(service.transitionEvent(id,e.revision+1,'PUBLISHED','PUBLISHED'));
});
test('event-scoped manager cannot attach another event media or use the retired submission mutation',async()=>{
 const id=await draft(),d=await complete(id),other=await draft(),media=randomUUID();await db.pool.query("INSERT INTO media_objects(id,organizer_id,event_id,object_key,content_type,bytes) VALUES($1,$2,$3,$4,'image/webp',100)",[media,owner.id,other,`${media}.webp`]);
 actor=await buyer('ORGANIZER_MANAGER',[id]);await assert.rejects(service.saveEvent(id,2,{...d,image:`/api/media/${media}`}),{status:404});
 const route=load('app/api/organizador/eventos/submit/route.ts');assert.equal((await route.POST(new Request('https://local/api/organizador/eventos/submit',{method:'POST'}))).status,410);
});
