'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {Button,Field,Notice} from '@/components/tc/ui';
import {emptyDraft,type Draft} from '@/lib/organizer/model';
import type {Event} from '@/lib/events';
import type {Proposal,ProviderStatus} from '@/lib/ai/model';
import Preview from '@/components/organizer/Preview';
import DraftFields from './DraftFields';

export default function Simulator({status}:{status:ProviderStatus}){
 const [prompt,setPrompt]=useState(''),[draft,setDraft]=useState<Draft|null>(null),[proposal,setProposal]=useState<Proposal|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(false),[saved,setSaved]=useState(false),[confirmed,setConfirmed]=useState(false),[organizations,setOrganizations]=useState<{id:string;name:string}[]>([]),[organization,setOrganization]=useState(''),[tab,setTab]=useState('edit');
 const heading=useRef<HTMLHeadingElement>(null);
 useEffect(()=>{let live=true;fetch('/api/ai/simulator').then(r=>r.json()).then(d=>{if(!live)return;if(d.draft){setDraft(d.draft.draft);setProposal(d.draft.proposal);setSaved(true);setMessage('Borrador recuperado en este navegador. Revisa tus cambios antes de continuar.');}setOrganizations(d.organizations||[]);setOrganization(d.organizations?.[0]?.id||'');}).catch(()=>{if(live)setMessage('No pudimos recuperar el borrador. Intenta recargar.');});return()=>{live=false;};},[]);
 async function request(body:object){const r=await fetch('/api/ai/simulator',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw new Error(d.error||'No se pudo completar la solicitud.');return d;}
 async function run(action:'generate'|'save'|'claim'){
  setBusy(true);setMessage('');setError(false);
  try{
   if(action==='generate'){const d=await request({action,prompt,requestId:crypto.randomUUID()});setDraft(d.draft);setProposal(d.proposal);setSaved(true);setConfirmed(false);setMessage('Propuesta validada y conservada. Todos los campos son sugerencias por revisar.');setTimeout(()=>heading.current?.focus(),0);}
   if(action==='save'){await request({action,draft});setSaved(true);setMessage('Borrador conservado durante 7 días desde su creación, en este navegador. Puedes crear tu cuenta o iniciar sesión.');}
   if(action==='claim'){await request({action:'save',draft});const d=await request({action,organizerId:organization,confirmed});window.location.assign(`/organizador/eventos/${d.id}?section=editor`);}
  }catch(e){setError(true);setMessage(e instanceof Error?e.message:'No hay conexión. Tu texto y cambios se conservan en esta pantalla.');}finally{setBusy(false);}
 }
 const preview:Event|null=draft?{id:'simulator',slug:'simulator',title:draft.title||'Nombre por confirmar',description:draft.description||'Descripción por confirmar',city:draft.city||'Ciudad por confirmar',venue:draft.venue||'Recinto por confirmar',dateISO:draft.date_iso||'',endISO:draft.end_at||undefined,timezone:draft.timezone,address:draft.address,agePolicy:draft.age_policy,accessInfo:draft.access_info,faq:draft.faq,image:'',organizerName:'Tu organización',categoryName:draft.category_slug,ticketTypes:draft.tiers.map(t=>({id:t.id,name:t.name||'Entrada por confirmar',priceCLP:t.price_clp,capacity:t.capacity,maxPerOrder:t.max_per_order}))}:null;
 return <div className="stack ai-simulator" aria-busy={busy}><div className="detail-columns"><section className="panel stack"><h2>¿Qué te gustaría crear?</h2><Field label="Describe tu evento" hint="Incluye solo información del evento. Evita emails, teléfonos, datos de asistentes y credenciales."><textarea rows={6} maxLength={4000} value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder={'Concierto “Encuentro del Sur” en Santiago para 800 personas. General $15.000, VIP $30.000.'}/></Field><Notice>{status.label}</Notice><div className="row"><Button disabled={busy||!status.enabled||prompt.trim().length<10} onClick={()=>void run('generate')}>{busy?'Preparando propuesta…':'Generar propuesta'}</Button><Button variant="quiet" disabled={busy} onClick={()=>{setDraft({...emptyDraft});setProposal(null);setSaved(false);}}>Comenzar manualmente</Button></div></section><aside className="stack"><p className="eyebrow">De la idea al encuentro</p><h2>Tu criterio,<br/>en cada decisión.</h2><p className="muted">Revisa el texto, ajusta las entradas y mira cómo se verá tu evento. Guardarlo como borrador requiere una organización autorizada.</p><p className="hint">Precios en CLP. Las fechas, el recinto y las condiciones de acceso deben ser confirmados por ti.</p></aside></div><div role="status" aria-live="polite">{busy?<Notice>Generando o guardando. Espera a que termine la solicitud.</Notice>:message&&<Notice error={error}>{message}</Notice>}</div>
 {draft&&<section className="stack"><h2 ref={heading} tabIndex={-1}>De propuesta a borrador</h2>{proposal&&<><p className="eyebrow">{proposal.source==='LOCAL_RULES'?'Reglas locales · no es una respuesta de IA':'Propuesta generada con IA'} · revisión obligatoria</p>{proposal.warnings.map((w,i)=><p className="hint" key={i}>{w}</p>)}{proposal.missing.length>0&&<Notice>Pendiente de confirmar: {proposal.missing.join(' · ')}</Notice>}</>}<nav className="tabs" aria-label="Revisión del simulador"><button aria-current={tab==='edit'?'page':undefined} onClick={()=>setTab('edit')}>Editar propuesta</button><button aria-current={tab==='preview'?'page':undefined} onClick={()=>setTab('preview')}>Vista previa</button><button aria-current={tab==='save'?'page':undefined} onClick={()=>setTab('save')}>Guardar y continuar</button></nav>{tab==='edit'&&<DraftFields draft={draft} onChange={d=>{setDraft(d);setSaved(false);setConfirmed(false);}}/>}{tab==='preview'&&preview&&<><Notice>Vista previa de tus sugerencias. No hay evento publicado ni compras habilitadas.</Notice><Preview event={preview}/></>}{tab==='save'&&<section className="panel stack"><h3>Conserva tu idea y continúa con tu organización</h3><p>{saved?'Tu borrador está conservado en este navegador.':'Tienes cambios sin conservar.'} La cuenta debe estar verificada, aprobada y completar su seguridad. El borrador vence a los 7 días; vuelve a este simulador desde el mismo navegador.</p><Button disabled={busy} onClick={()=>void run('save')}>Conservar borrador</Button>{saved&&!organizations.length&&<div className="row"><Link className="btn secondary" href="/organizador/registro">Crear cuenta de organizador</Link><Link className="btn secondary" href="/organizador/login?from=%2Forganizador%3Fsimulator%3D1">Iniciar sesión para continuar</Link></div>}{organizations.length>0&&<><Field label="Organización que recibirá el borrador"><select value={organization} onChange={e=>setOrganization(e.target.value)}>{organizations.map(o=><option value={o.id} key={o.id}>{o.name}</option>)}</select></Field><Notice>Se creará un evento privado con los campos que revisaste. Las entradas estarán inactivas hasta que las revises en el editor.</Notice><Field label="Revisé y confirmo fechas, ubicación, edad, precios y capacidades de este borrador"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/></Field><Button disabled={busy||!confirmed||!organization} onClick={()=>void run('claim')}>Crear borrador en mi organización</Button></>}</section>}</section>}
 </div>;
}
