import Link from 'next/link';
import {notFound} from 'next/navigation';
import {adminList,sections,sectionCapability,type Section} from '@/lib/admin/queries.server';
import {adminContext} from '@/lib/admin/policy.server';
import {refundProviderStatus} from '@/lib/payments/refunds.server';
import Records from '@/components/admin/Records';
import Action from '@/components/admin/Action';
import {legacySubmissions} from '@/lib/admin/legacy.server';
export default async function Page({params,searchParams}:{params:Promise<{section:string}>;searchParams:Promise<Record<string,string>>}){
 const {section:raw}=await params;if(!(Object.hasOwn(sections,raw))||raw==='overview')notFound();const section=raw as Section,filters=await searchParams,ctx=await adminContext(),can=(c:string)=>ctx.capabilities.includes(c);
 if(!can(sectionCapability(section)))return <div className="admin-panel"><h1>Acceso restringido</h1><p>Tu cuenta no tiene permiso para esta sección.</p><Link href="/admin">Volver al resumen</Link></div>;
 if(section==='settings')return <div className="stack"><header className="admin-heading"><p className="eyebrow">PLATAFORMA</p><h1>Configuración operativa</h1></header><div className="admin-panel"><h2>Proveedores y alcance</h2><p>Reembolsos Stripe: {refundProviderStatus().enabled?'habilitados para órdenes completas':'deshabilitados'}. Webpay y Flow: revisión manual.</p><p>La habilitación se configura en el servidor. Las credenciales nunca se muestran ni se editan aquí.</p><p>Comisiones, impuestos, retención de comisiones reembolsadas y calendario de pago requieren una política aprobada.</p><Link href="/admin/commissions">Versiones de comisión →</Link></div><div className="admin-panel"><h2>Acceso y seguridad</h2><p>{ctx.role} · {ctx.capabilities.join(' · ')}</p><Link href="/security?kind=ADMIN">Administrar mi autenticación y sesiones</Link><p>Los permisos restringidos se asignan mediante administración de identidad del servidor. Ninguna configuración permite omitir MFA.</p></div></div>;
 const data=section==='events'&&filters.legacy==='1'?await legacySubmissions(Number(filters.page)):await adminList(section,filters);
 const actionQuery=new URLSearchParams(filters);const page=Number(filters.page)||1;
 return <div className="stack"><header className="admin-heading"><p className="eyebrow">OPERACIONES / {ctx.role}</p><h1>{sections[section]}</h1><p className="hint">50 registros por página. Acceso y operaciones registrados.</p></header>
 {section==='orders'&&<p className="admin-warning">Busca el correo exacto, ID de orden o ID de entrada. Los datos personales se muestran al abrir una orden.</p>}
 {section==='events'&&<p><Link href="?legacy=1">Revisar solicitudes anteriores</Link> · <Link href="/admin/events">Eventos actuales</Link></p>}
 {section==='events'&&filters.legacy==='1'&&<p className="admin-warning">Solicitudes anteriores conservadas. No son eventos publicables. Abre la revisión para resolverlas sin convertir automáticamente sus datos.</p>}
 {section==='commissions'&&<p className="admin-warning">Sin tasa predeterminada. Cada compra conserva su versión. Porcentaje sobre el monto cobrado, redondeado hacia abajo, más un fijo por orden; ambos se descuentan del organizador según la política que registres. No cambia el precio al comprador.</p>}
 {section==='settlements'&&<p className="admin-warning">Saldo calculado = cobros verificados − reembolsos confirmados − comisión histórica + ajustes documentados. El borrador no incorpora impuestos ni tarifas desconocidas. Registrar un pago externo no realiza una transferencia.</p>}
 <form className="admin-filters">{filters.legacy&&<input type="hidden" name="legacy" value="1"/>}{[['q',section==='orders'?'Correo o ID exacto':'Nombre o ID'],['state','Estado'],['event','ID de evento'],['organizer','ID de organizador'],['from','Desde (UTC)'],['to','Hasta (UTC)']].map(([name,label])=><label className="field" key={name}><span>{label}</span><input name={name} defaultValue={filters[name]} type={['from','to'].includes(name)?'date':'text'} maxLength={200}/></label>)}<button className="btn primary">Aplicar filtros</button><Link className="btn secondary" href={`/admin/${section}`}>Limpiar</Link></form>
 {section==='reports'&&<a className="btn secondary" href={`/api/admin/export?${actionQuery}`}>Exportar pagos CSV (hasta 31 días / 1000 registros)</a>}
 <Records rows={data.rows} section={filters.legacy?undefined:section}/>
 {section==='events'&&filters.legacy==='1'&&can('moderation.write')&&data.rows.map(row=><Action key={String(row.id)} action="legacy.review" target={String(row.id)} label={`Resolver solicitud ${row.id}`} description="Conserva el envío original. Solicita al organizador que prepare un borrador actual antes de publicar." fields={[{name:'state',label:'Resolución',options:['REJECTED','NEEDS_INFORMATION']}]} />)}
 <div className="row">{page>1&&<Link className="btn secondary" href={`?${new URLSearchParams({...filters,page:String(page-1)})}`}>Anterior</Link>}{data.hasMore&&<Link className="btn secondary" href={`?${new URLSearchParams({...filters,page:String(page+1)})}`}>Siguiente</Link>}</div>
 {section==='commissions'&&can('configuration.write')&&<Action action="commission.create" target="policy" label="Programar comisión" description="Solo ventas futuras. Registra la referencia de la política aprobada y la base de cálculo acordada." fields={[{name:'scope',label:'Alcance',options:['GLOBAL','ORGANIZER','EVENT']},{name:'scopeId',label:'ID del organizador o evento (vacío para global)',required:false},{name:'basisPoints',label:'Puntos base: 100 = 1 %',type:'number'},{name:'fixedClp',label:'Fijo CLP por orden',type:'number'},{name:'effectiveAt',label:'Vigente desde',type:'datetime-local'},{name:'policyReference',label:'Referencia de política aprobada'}]}/>}
 {section==='support'&&can('support.write')&&<Action action="support.create" target="new" label="Abrir caso" description="Usa contexto mínimo. No pegues claves, datos bancarios ni credenciales en notas internas." fields={[{name:'subject',label:'Asunto'},{name:'orderId',label:'ID de orden',required:false},{name:'organizerId',label:'ID de organizador',required:false},{name:'eventId',label:'ID de evento',required:false}]}/>}
 </div>;
}
