'use client';
import {useEffect,useRef,useState} from 'react';
import {Button,Notice} from '@/components/tc/ui';
export default function QRScanner({onResult,paused=false,cooldownMs=1500}:{onResult:(text:string)=>void;paused?:boolean;cooldownMs?:number}){
 const video=useRef<HTMLVideoElement>(null),controls=useRef<{stop:()=>void}|null>(null),generation=useRef(0),starting=useRef(false),last=useRef({text:'',at:0}),callback=useRef(onResult),blocked=useRef(paused);
 const [state,setState]=useState('idle'),[error,setError]=useState('');
 useEffect(()=>{callback.current=onResult;blocked.current=paused;},[onResult,paused]);
 function stop(){generation.current++;controls.current?.stop();controls.current=null;const stream=video.current?.srcObject;if(stream instanceof MediaStream)stream.getTracks().forEach(t=>t.stop());starting.current=false;setState('idle');}
 useEffect(()=>()=>{generation.current++;controls.current?.stop();},[]);
 async function start(){if(starting.current||controls.current)return;setError('');if(!navigator.mediaDevices?.getUserMedia){setError('Este dispositivo no tiene una cámara disponible en una conexión segura. Usa el código de entrada.');return;}starting.current=true;const version=++generation.current;setState('requesting');
 try{const {BrowserQRCodeReader}=await import('@zxing/browser');if(version!==generation.current)return;const reader=new BrowserQRCodeReader();const c=await reader.decodeFromConstraints({video:{facingMode:{ideal:'environment'}},audio:false},video.current!,result=>{if(version!==generation.current)return;const text=result?.getText();if(!text||blocked.current)return;const now=Date.now();if(now-last.current.at<cooldownMs||text===last.current.text&&now-last.current.at<5000)return;last.current={text,at:now};callback.current(text);});if(version!==generation.current){c.stop();return;}controls.current=c;setState('ready');}
 catch(e){if(version!==generation.current)return;const name=e instanceof Error?e.name:'';setError(name==='NotAllowedError'?'Permiso de cámara denegado. Habilítalo en el navegador o usa el código de entrada.':name==='NotFoundError'?'No se encontró cámara. Usa el código de entrada.':'No pudimos abrir la cámara. Intenta nuevamente o usa el código de entrada.');setState('idle');}finally{starting.current=false;}}
 return <section className="stack"><video ref={video} playsInline muted aria-label="Cámara para leer QR" className="scanner-video"/><p role="status">{state==='requesting'?'Solicitando permiso de cámara…':state==='ready'?paused?'Lectura pausada mientras revisas el resultado.':'Cámara lista. Acerca un QR.':'Cámara apagada.'}</p>{error&&<Notice error>{error}</Notice>}<div className="row"><Button disabled={state!=='idle'||paused} onClick={()=>void start()}>Abrir cámara</Button><Button variant="quiet" disabled={state==='idle'} onClick={stop}>Cerrar cámara</Button></div></section>;
}
