import Link from 'next/link';
import { notFound } from 'next/navigation';
import { AccessError } from '@/lib/access.server';
import { readEvent } from '@/lib/organizer/events.server';
import { accessMetrics,activity,attendees,sales,staffForEvent } from '@/lib/organizer/operations.server';
import { checklist } from '@/lib/organizer/model';
import { formatCLP,type Event } from '@/lib/events';
import { eventMedia } from '@/lib/media';
import { dateLabel } from '@/lib/discovery';
import { PageHeading,Notice,Field } from '@/components/tc/ui';
import { EventState } from '@/components/organizer/EventList';
import Editor from '@/components/organizer/Editor';
import Lifecycle from '@/components/organizer/Lifecycle';
import Preview from '@/components/organizer/Preview';
import Staff from '@/components/organizer/Staff';
import AI from '@/components/organizer/AI';
const sections=[['overview','Resumen',''],['editor','Editor','event.edit'],['tiers','Entradas','event.read'],['sales','Ventas','finance.read'],['attendees','Asistentes','attendees.read'],['promotions','Promociones','event.edit'],['staff','Staff','staff.manage'],['access','Acceso','scanner.read'],['analytics','Analítica','finance.read'],['settings','Ajustes','event.edit'],['preview','Vista previa','event.read'],['checklist','Publicación','event.edit'],['ai','TicketChile AI','event.edit']];
export default async function Center({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{section?:string;q?:string;status?:string;page?:string}>}){
 const {id}=await params,p=await searchParams,e=await readEvent(id).catch(err=>{if(err instanceof AccessError&&err.status===404)notFound();throw err;});
 const section=p.section||'overview',descriptor=sections.find(s=>s[0]===section);if(!descriptor||descriptor[2]&&!e.capabilities.includes(descriptor[2]))notFound();
 const allowed=sections.filter(s=>!s[2]||e.capabilities.includes(s[2])),url=(s:string)=>`/organizador/eventos/${id}?section=${s}`,can=(c:string)=>e.capabilities.includes(c),checks=checklist(e);
 let content:React.ReactNode;
 if(section==='editor')content=<Editor key={e.id} event={e}/>;
 else if(section==='tiers')content=<div className="stack"><div className="row between"><h2>Inventario y tipos de entrada</h2>{can('event.edit')&&<Link href={url('editor')}>Editar entradas →</Link>}</div><p className="muted">{e.tiers.reduce((n,t)=>n+t.capacity,0)} asignadas / {e.capacity} aforo</p>{e.tiers.length?e.tiers.map(t=><div className="history-row" key={t.id}><div><h3>{t.name}</h3><p className="hint">{t.description}</p><p className="hint">{t.active?'Activa':'Inactiva'} · {t.visible?'Visible':'Privada / no disponible para venta pública'}</p><p className="hint">{t.sales_start?dateLabel(t.sales_start):'Inicio inmediato'} → {t.sales_end?dateLabel(t.sales_end):'Hasta el inicio del evento'}</p></div><div className="stack-sm"><span className="mono">${formatCLP(t.price_clp)}</span><span className="hint">{t.sold||0} vendidas · {t.held||0} reservadas · {Math.max(0,t.capacity-(t.sold||0)-(t.held||0))} disponibles</span><span className="hint">Máximo {t.max_per_order} por compra</span></div></div>):<Notice>Añade tus tipos de entrada desde el editor.</Notice>}</div>;
 else if(section==='sales'||section==='analytics'){
  const data=await sales(id);content=<div className="stack"><h2>{section==='sales'?'Ventas verificadas':'Analítica del evento'}</h2><div className="org-summary"><div><span className="mono">${formatCLP(Number(data.summary.gross))}</span><span>Bruto verificado CLP</span></div><div><span className="mono">{data.summary.orders}</span><span>Órdenes</span></div><div><span className="mono">{data.summary.review}</span><span>Pagos requieren revisión</span></div></div><Notice>Hechos: pagos confirmados por proveedor. Neto, impuestos, liquidaciones y conversión no están calculados. No hay una inferencia de IA.</Notice><h3>Pagos por método y estado</h3>{data.payments.map(r=><div className="history-row" key={`${r.provider}-${r.status}`}><span>{r.provider} / {r.status}</span><span className="mono">{r.count}</span></div>)}{!data.payments.length&&<p className="muted">Aún no hay pagos.</p>}<h3>Entradas emitidas por tipo</h3>{data.tiers.map(t=><div className="history-row" key={t.ticket_type_name}><span>{t.ticket_type_name} · {t.qty} unidades</span><span className="mono">${formatCLP(Number(t.gross))}</span></div>)}<h3>Ventas por día · últimos 60 días con actividad</h3>{data.timeline.map(t=><div className="history-row" key={t.day}><span>{t.day}</span><span className="mono">${formatCLP(Number(t.gross))}</span></div>)}</div>;
 }else if(section==='attendees'){
  const page=Math.max(1,Number(p.page)||1),data=await attendees(id,p.q,p.status,page);content=<div className="stack"><div className="row between"><h2>Asistentes · {data.total}</h2>{can('attendees.export')&&<a className="btn secondary" href={`/api/scanner/export?eventId=${id}`}>Exportar CSV</a>}</div><form className="org-filter"><input type="hidden" name="section" value="attendees"/><Field label="Nombre, email o ticket"><input name="q" maxLength={120} defaultValue={p.q}/></Field><Field label="Estado"><select name="status" defaultValue={p.status||''}><option value="">Todos</option><option value="VALID">Sin usar</option><option value="USED">Ingresó</option><option value="CANCELLED">Cancelada</option></select></Field><button className="btn secondary">Buscar</button></form>{data.rows.map(t=><article className="history-row" key={t.id}><div><h3>{t.owner_email||'Titular sin email'}</h3><p className="hint">Comprador: {t.buyer_name} · {t.buyer_email}</p><p>{t.ticket_type_name}</p><p className="hint">Ticket {t.id} · Orden {t.order_id}</p></div><div><span className="status">{t.status==='USED'?'Ingresó':t.status==='VALID'?'Sin usar':'Cancelada'}</span><p className="hint">{t.used_at?dateLabel(t.used_at.toISOString()):'Sin check-in'}</p></div></article>)}{!data.rows.length&&<Notice>No hay asistentes con estos filtros.</Notice>}<div className="row">{page>1&&<Link href={`${url('attendees')}&page=${page-1}&q=${encodeURIComponent(p.q||'')}&status=${p.status||''}`}>← Anterior</Link>}{page*50<data.total&&<Link href={`${url('attendees')}&page=${page+1}&q=${encodeURIComponent(p.q||'')}&status=${p.status||''}`}>Siguiente →</Link>}</div><p className="hint">Reenvíos operativos, cortesías y comunicaciones masivas se habilitarán en M8. No se muestran QR de compradores.</p></div>;
 }else if(section==='staff'){const data=await staffForEvent(id);content=<Staff organizerId={e.organizer_id} eventId={id} {...data}/>;}
 else if(section==='access'){const data=await accessMetrics(id);content=<div className="stack"><h2>Acceso al evento</h2><div className="org-summary"><div><span className="mono">{data.issued}</span><span>Tickets emitidos</span></div><div><span className="mono">{data.checked}</span><span>Ingresaron</span></div><div><span className="mono">{data.cancelled}</span><span>Cancelados</span></div></div><Notice>Scanner con autorización de evento en servidor. Se requiere conexión; no hay modo offline.</Notice><p>{e.access_info||'Completa las instrucciones de acceso desde el editor.'}</p>{['CANCELLED','ENDED'].includes(e.lifecycle)?<Notice>El acceso está cerrado para este evento.</Notice>:<Link className="btn" href={`/scanner/${id}`}>Abrir scanner →</Link>}{can('staff.manage')&&<Link href={url('staff')}>Revisar staff y permisos de puerta →</Link>}</div>;}
 else if(section==='preview'){
  const event:Event={id:e.id,slug:e.slug,title:e.title||'Nombre por confirmar',city:e.city||'Ciudad por confirmar',venue:e.venue||'Recinto por confirmar',dateISO:e.date_iso||'',timezone:e.timezone,endISO:e.end_at||undefined,address:e.address,agePolicy:e.age_policy,accessInfo:e.access_info,faq:e.faq,image:eventMedia(e.image,e.id),hero:{desktop:eventMedia(e.hero_desktop||e.image,e.id,'desktop'),mobile:eventMedia(e.hero_mobile||e.image,e.id,'mobile')},description:e.description||'Descripción por confirmar',organizerName:e.organizer_name,categoryName:e.category_slug,ticketTypes:e.tiers.filter(t=>t.visible).map(t=>({id:t.id,name:t.name,priceCLP:t.price_clp,capacity:t.capacity,maxPerOrder:t.max_per_order}))};
  content=<div className="stack"><Notice>Vista privada de la última versión guardada. Faltan {checks.filter(c=>!c.ok).length} requisitos. La compra está deshabilitada.</Notice><Preview event={event}/></div>;
 }else if(section==='checklist'||section==='settings')content=<div className="stack"><h2>{section==='settings'?'Ajustes de este evento':'Revisar antes de publicar'}</h2>{checks.map(c=><div className="history-row" key={c.label}><span>{c.label}</span><span className="status">{c.ok?'Completo':'Pendiente'}</span></div>)}<div className="history-row"><span>Organizador verificado, aprobado y activo</span><span className="status">Confirmado por servidor</span></div><Notice>Enviar a revisión congela la versión revisada. Editar devuelve el estado a borrador. No existe aprobación automática ni plazo prometido.</Notice>{can('staff.manage')?<Lifecycle event={e}/>:<Notice>El propietario debe confirmar publicación, pausa o cancelación.</Notice>}{e.cancellation_followup&&<Notice error>Cancelación registrada. Reembolsos y comunicaciones requieren revisión operativa. No se ejecutó ningún reembolso.</Notice>}</div>;
 else if(section==='promotions')content=<Notice>Promociones, códigos y cortesías están previstos para M8. No hay promociones activas simuladas ni acciones automáticas de IA.</Notice>;
 else if(section==='ai')content=<AI event={e} local={process.env.NODE_ENV!=='production'&&process.env.ORGANIZER_AI_ADAPTER==='local'}/>;
 else {
  const logs=can('audit.read')?await activity(id):[];content=<div className="stack"><div className="org-summary"><div><span className="mono">{e.tiers.reduce((n,t)=>n+(t.sold||0),0)}</span><span>Entradas vendidas</span></div><div><span className="mono">{e.capacity}</span><span>Aforo total</span></div><div><span className="mono">{e.tiers.length}</span><span>Tipos de entrada</span></div></div>{can('event.edit')&&<Notice>{checks.filter(c=>!c.ok).length} requisitos pendientes. <Link href={url('checklist')}>Revisar publicación →</Link></Notice>}<h2>Operar este evento</h2><div className="org-quick">{allowed.filter(s=>['editor','attendees','access','sales','staff','ai'].includes(s[0])).map(s=><Link className="panel" key={s[0]} href={url(s[0])}>{s[1]} →</Link>)}</div>{e.cancellation_followup&&<Notice error>Cancelado: revisión de reembolsos y comunicaciones pendiente.</Notice>}{can('audit.read')&&<><h2>Actividad reciente</h2>{logs.map((l,i)=><div className="history-row" key={i}><span>{l.action}</span><span className="hint">{dateLabel(l.created_at.toISOString())}</span></div>)}{!logs.length&&<p className="muted">Sin actividad registrada.</p>}</>}</div>;
 }
 return <div className="stack"><Link className="hint" href="/organizador/eventos">← Mis eventos</Link><div className="row between"><PageHeading eyebrow="Centro del evento" title={e.title||'Evento sin nombre'}>{e.date_iso?dateLabel(e.date_iso):'Fecha pendiente'} · {e.city||'Ciudad pendiente'} · {e.organizer_name}</PageHeading><EventState state={e.lifecycle}/></div><nav className="tabs org-event-tabs" aria-label="Centro del evento">{allowed.map(s=><Link aria-current={section===s[0]?'page':undefined} key={s[0]} href={url(s[0])}>{s[1]}</Link>)}</nav>{content}</div>;
}
