'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { Button, Field, Notice } from './ui';
type Detail={own:boolean;eligible:boolean;pending:{id:string;recipient:string;expiresAt:string}|null;history:{sequence:number;owner:string;acquiredAt:string;initiatedAt:string|null}[]};
export default function TicketTransfer({id,detail:initialDetail}:{id:string;detail:Detail}) {
  const [detail,setDetail]=useState(initialDetail);
  const router=useRouter(),[busy,setBusy]=useState(false),[result,setResult]=useState(''),[error,setError]=useState(false),[key,setKey]=useState('');
  async function action(action:string,recipient?:string) {
    setBusy(true);setResult('');const requestKey=key||crypto.randomUUID();setKey(requestKey);
    try {const r=await fetch('/api/tickets/transfer',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,ticketId:id,id:detail.pending?.id,recipient,requestKey})});const b=await r.json();setError(!r.ok);setResult(r.ok?action==='cancel'?'Invitación cancelada.':action==='resend'?'Nueva invitación en cola. El enlace anterior ya no es válido.':'Invitación en cola. Conservas tu entrada hasta que sea aceptada.':b.error);if(r.ok){setKey('');const refreshed=await fetch('/api/tickets/transfer',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'detail',ticketId:id})});if(refreshed.ok)setDetail(await refreshed.json());router.refresh();}}
    catch {setError(true);setResult('No pudimos conectar. Puedes reintentar la misma solicitud.');}finally{setBusy(false);}
  }
  return <section className="panel stack" style={{overflowWrap:"anywhere"}}><h2>{detail.own?'Transferir entrada':'Entrada transferida'}</h2>{!detail.own?<Notice>Este registro es histórico. Tu QR y tu pase Wallet anteriores ya no permiten ingresar.</Notice>:detail.pending?<><Notice>Transferencia pendiente</Notice><p>Destinatario: {detail.pending.recipient}</p><p className="hint">Vence: {new Date(detail.pending.expiresAt).toLocaleString('es-CL')}</p><p className="hint">{detail.eligible?"Conservas el acceso hasta la aceptación. Si usas la entrada, la transferencia no podrá completarse.":"La entrada ya no permite aceptar esta invitación. Puedes cancelarla."}</p><div className="row"><Button disabled={busy} variant="secondary" onClick={()=>action('cancel')}>Cancelar transferencia</Button><Button disabled={busy} variant="secondary" onClick={()=>action('resend')}>Reenviar invitación</Button></div></>:detail.eligible?<form className="stack" onSubmit={e=>{e.preventDefault();action('initiate',String(new FormData(e.currentTarget).get('recipient')));}}><p>El destinatario deberá verificar su correo y aceptar. Al aceptar, tu QR y tu pase Wallet dejarán de permitir el ingreso.</p><Field label="Correo del destinatario"><input name="recipient" type="email" autoComplete="off" required maxLength={254} /></Field><Button disabled={busy}>{busy?'Procesando…':'Enviar invitación'}</Button></form>:<Notice>La transferencia no está disponible para esta entrada. Depende de su estado y de la política del evento.</Notice>}{result&&<Notice error={error}>{result}</Notice>}<h3>Historial de titularidad</h3><ol className="stack-sm">{detail.history.map(h=><li key={h.sequence}><strong>{h.sequence===0?'Titularidad inicial registrada':`Transferencia ${h.sequence}`}</strong><p className="hint">{h.owner} · {new Date(h.acquiredAt).toLocaleString('es-CL')}</p>{h.initiatedAt&&<p className="hint">Iniciada: {new Date(h.initiatedAt).toLocaleString('es-CL')}</p>}</li>)}</ol></section>;
}
