import { AccessError } from '@/lib/access.server';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import {adminDetail,sections,sectionCapability,type Section} from '@/lib/admin/queries.server';
import {adminContext} from '@/lib/admin/policy.server';
import Records,{RecordFields} from '@/components/admin/Records';
import Action from '@/components/admin/Action';
import {refundProviderStatus} from '@/lib/payments/refunds.server';
import Media from '@/components/tc/Media';
const relatedLabels:Record<string,string>={events:'Portafolio de eventos',staff:'Equipo activo',tiers:'Entradas y stock',tickets:'Entradas de la orden',delivery:'Entrega de correos',evidence:'Evidencia del proveedor',commission:'Comisión al comprar',payments:'Pagos incluidos',adjustments:'Ajustes documentados',payout:'Registro de pago externo',notes:'Notas internas',history:'Historial de decisiones'};
export default async function Page({params}:{params:Promise<{section:string;id:string}>}){
 const {section:raw,id}=await params;if(!(Object.hasOwn(sections,raw)))notFound();const section=raw as Section,ctx=await adminContext(),can=(c:string)=>ctx.capabilities.includes(c);
 if(!can(sectionCapability(section)))return <div className="admin-panel"><h1>Acceso restringido</h1><p>Tu cuenta no tiene permiso para este registro.</p><Link href="/admin">Volver al resumen</Link></div>;
 const {row,related}=await adminDetail(section,id).catch(error=>{if(error instanceof AccessError && error.status===404)notFound();throw error;});
 return <div className="stack"><Link href={`/admin/${section}`}>← {sections[section]}</Link><header className="admin-heading"><p className="eyebrow">REVISIÓN OPERATIVA</p><h1>{String(row.title||row.display_name||row.subject||sections[section])}</h1><p className="hint">{id}</p></header><div className="admin-panel"><RecordFields row={Object.fromEntries(Object.entries(row).filter(([key])=>!['image','hero_desktop','hero_mobile'].includes(key)))}/></div><div className="admin-actions">
 {section==='organizers'&&can('moderation.write')&&<Action action="organizer.review" target={id} label="Decidir verificación" description="Aprobar habilita la operación del organizador; suspender revoca su acceso. La verificación de correo es independiente." fields={[{name:'state',label:'Decisión',options:['APPROVED','NEEDS_INFORMATION','REJECTED','SUSPENDED']}]}/>}
 {section==='events'&&<><section className="stack"><h2>Imágenes del evento</h2><div className="org-three">{['image','hero_desktop','hero_mobile'].map((field,i)=><figure key={field}><div className="org-media"><Media src={String(row[field]||'')} alt={['Imagen principal','Portada escritorio','Portada móvil'][i]} sizes="(max-width:800px) 80vw, 300px"/></div><figcaption>{['Imagen principal','Portada escritorio','Portada móvil'][i]}</figcaption></figure>)}</div></section><Link href={`/admin/payments?event=${id}`}>Pagos afectados y revisión de reembolsos →</Link>{can('moderation.write')&&<Action action="event.moderate" target={id} label="Moderar evento" description="Publicar exige la lista de publicación completa. Pausar bloquea nuevas ventas y republicación. Cancelar invalida entradas vigentes, libera reservas y crea seguimiento; no ejecuta reembolsos." values={{revision:row.revision}} fields={[{name:'state',label:'Decisión',options:['PUBLISHED','PAUSED','CHANGES_REQUESTED','CANCELLED','ENDED']}]}/>} {can('settlement.write')&&<Action action="settlement.create" target={id} label="Preparar liquidación" description="Incluye los pagos emitidos, verificados y aún no liquidados del evento. Bloquea pagos sin comisión histórica conocida o con reembolsos pendientes."/>}</>}
 {section==='orders'&&can('support.write')&&<Action action="order.resend" target={id} label="Reenviar entradas vigentes" description="Encola la entrega al titular actual de cada entrada válida. No permite cambiar destinatarios ni enviar texto arbitrario."/>}
 {section==='orders'&&can('finance.read')&&<Link href={`/admin/payments?q=${id}`}>Ver pagos de esta orden →</Link>}
 {section==='payments'&&can('refund.write')&&<><Action action="payment.finalize" target={id} label="Reintentar emisión local" description="Reutiliza la evidencia persistida y el emisor idempotente. No consulta ni cobra al proveedor."/><Action action="payment.review" target={id} label="Marcar para revisión" description="Marca un pago sin emisión para seguimiento operativo. No altera la evidencia de pago."/><Action action="refund.request" target={id} label="Solicitar reembolso completo" description="Prepara una revisión del total pagado. No ejecuta dinero. Las entradas usadas y pagos ya liquidados requieren revisión manual."/></>}
 {section==='refunds'&&can('refund.write')&&<><p className="admin-warning">Proveedor: {row.provider}. Parciales no habilitados. La elegibilidad depende de una política aprobada.</p>{row.status==='REQUESTED'&&<Action action="refund.approve" target={id} label="Aprobar solicitud" description="Registra la política que permite devolver el total. La ejecución del proveedor es un paso separado." fields={[{name:'policyReference',label:'Referencia de política aprobada'}]}/>} {['REQUESTED','APPROVED'].includes(String(row.status))&&<Action action="refund.reject" target={id} label="Rechazar solicitud" description="Cierra una solicitud que aún no se ejecutó."/>}{row.provider==='stripe'&&['APPROVED','PROCESSING','UNKNOWN'].includes(String(row.status))&&(refundProviderStatus().enabled?<Action action="refund.execute" target={id} label="Ejecutar / conciliar Stripe" description="Envía el reembolso completo o recupera su resultado con la misma clave. Un resultado incierto mantiene el bloqueo de acceso hasta conciliar."/>:<p className="notice">Ejecución Stripe deshabilitada en este entorno. No se moverá dinero.</p>)}</>}
 {section==='settlements'&&can('settlement.write')&&<>{row.status==='DRAFT'&&<><Action action="settlement.adjust" target={id} label="Registrar ajuste contable" description="Monto positivo acredita al organizador; negativo deduce. Documenta la evidencia y política del ajuste, incluyendo tarifas, impuestos o devolución de comisiones cuando corresponda." fields={[{name:'amount',label:'Ajuste CLP con signo',type:'number'}]}/><Action action="settlement.approve" target={id} label="Aprobar liquidación" description="Congela el saldo revisado. No transfiere dinero ni impone un calendario de pago." fields={[{name:'policyReference',label:'Política / expediente contable'},{name:'accountingReviewed',label:'Revisé tarifas del procesador, impuestos, comisiones reembolsadas y ajustes',type:'checkbox'}]}/><Action action="settlement.cancel" target={id} label="Cancelar borrador" description="Libera los pagos para un nuevo cálculo, conservando la evidencia del borrador."/></>}{row.status==='APPROVED'&&<Action action="settlement.paid" target={id} label="Registrar pago externo realizado" description={`Registra únicamente una transferencia ya realizada fuera de TicketChile por ${row.net_clp} CLP. No inicia una transferencia bancaria.`} fields={[{name:'amount',label:'Monto transferido CLP',type:'number'},{name:'reference',label:'Referencia externa única'}]}/>}</>}
 {section==='support'&&can('support.write')&&<><Action action="support.state" target={id} label="Cambiar estado del caso" description="La resolución no cambia pagos ni entradas." fields={[{name:'state',label:'Estado',options:['OPEN','IN_PROGRESS','RESOLVED']}]}/><Action action="support.note" target={id} label="Agregar nota interna" description="Solo visible para administración autorizada. No se envía al comprador ni al organizador." fields={[{name:'note',label:'Nota interna'}]}/>{row.order_id&&<Link href={`/admin/orders/${row.order_id}`}>Abrir orden relacionada →</Link>}</>}
 </div>{Object.entries(related).map(([key,rows])=><section key={key}><h2>{relatedLabels[key]||key}</h2><Records rows={rows} section={key==='events'?'events':undefined}/></section>)}</div>;
}
