'use client';
import {useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {Button,Field,Notice} from '@/components/tc/ui';
import {emptyDraft,type Draft,type EventRecord} from '@/lib/organizer/model';
import type {Proposal} from '@/lib/organizer/proposals';
export default function AI({event,local}:{event:EventRecord;local:boolean}){
 const router=useRouter(),[prompt,setPrompt]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[proposal,setProposal]=useState<Proposal|null>(null),[values,setValues]=useState<Record<string,string>>({}),[accepted,setAccepted]=useState<string[]>([]),[priceConfirmation,setPriceConfirmation]=useState(false);
 async function propose(){setBusy(true);setMessage('');try{const r=await fetch(`/api/organizer/events/${event.id}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'proposal',prompt})});const d=await r.json();if(!r.ok)throw new Error(d.error);setProposal(d);setAccepted([]);setValues(Object.fromEntries(Object.entries(d.patch).map(([k,v])=>[k,typeof v==='string'?v:JSON.stringify(v,null,2)])));}catch(e){setMessage(e instanceof Error?e.message:'No hay conexión. Intenta nuevamente.');}finally{setBusy(false);}}
 async function apply(){if(!proposal)return;setBusy(true);setMessage('');try{const draft=Object.fromEntries(Object.keys(emptyDraft).map(k=>[k,event[k as keyof Draft]])) as Draft;for(const k of accepted){const value=['capacity','tiers'].includes(k)?JSON.parse(values[k]):values[k];if(k==='tiers')draft.tiers=[...event.tiers,...value];else Object.assign(draft,{[k]:value});}const r=await fetch(`/api/organizer/events/${event.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:proposal.baseRevision,draft,confirmPrices:priceConfirmation})});const d=await r.json();if(!r.ok)throw new Error(d.error);setProposal(null);setMessage('Cambios seleccionados guardados. El estado de publicación no se modifica automáticamente.');router.refresh();}catch(e){setMessage(e instanceof Error?e.message:'Propuesta inválida. Revisa los campos.');}finally{setBusy(false);}}
 return <section className="panel stack"><p className="eyebrow">TicketChile AI / Este evento</p><h2>De la idea a una propuesta revisable.</h2><Notice>{local?'Modo local de desarrollo: extracción por reglas, sin modelo de IA. Prueba la revisión usando un nombre entre comillas, ciudad y cantidades explícitas.':'Proveedor de IA pendiente de M7. Este espacio conserva tu borrador; no inventa precios, aforos ni direcciones.'}</Notice><Field label="Describe tu evento" hint="Solo se lee tu descripción y la versión de este evento. No se envían datos de asistentes o pagos a un proveedor."><textarea rows={6} maxLength={4000} value={prompt} onChange={e=>setPrompt(e.target.value)}/></Field><Button disabled={busy||prompt.length<10} onClick={()=>void propose()}>{local?'Preparar propuesta local':'Consultar disponibilidad de propuesta'}</Button>{proposal&&<div className="stack"><h3>Revisar cambios · versión {proposal.baseRevision}</h3>{proposal.warnings.map(w=><p className="hint" key={w}>{w}</p>)}{Object.keys(proposal.patch).map(k=><section className="org-tier stack" key={k}><h3>{k}</h3><div className="org-two"><div><p className="eyebrow">Actual</p><pre className="org-diff">{typeof event[k as keyof Draft]==='string'?String(event[k as keyof Draft]):JSON.stringify(event[k as keyof Draft],null,2)}</pre></div><Field label="Propuesto · editable"><textarea value={values[k]} onChange={e=>setValues(v=>({...v,[k]:e.target.value}))}/></Field></div><Field label={k==='tiers'?'Confirmo añadir estos tipos inactivos sin reemplazar los existentes':`Confirmo aplicar ${k}`}><input type="checkbox" checked={accepted.includes(k)} onChange={e=>setAccepted(a=>e.target.checked?[...a,k]:a.filter(x=>x!==k))}/></Field></section>)}{!Object.keys(proposal.patch).length&&<Notice>No se pudieron extraer campos explícitos. Continúa manualmente.</Notice>}<p>Falta confirmar: {proposal.missing.join(' · ')}</p><Field label="Confirmo precios y capacidades seleccionados para ventas futuras"><input type="checkbox" checked={priceConfirmation} onChange={e=>setPriceConfirmation(e.target.checked)}/></Field><div className="row"><Button disabled={busy||!accepted.length||(accepted.some(k=>['tiers','capacity'].includes(k))&&!priceConfirmation)} onClick={()=>void apply()}>Aplicar solo cambios confirmados</Button><Button variant="quiet" onClick={()=>setProposal(null)}>Rechazar propuesta</Button></div></div>}{message&&<Notice>{message}</Notice>}<Link href={`/organizador/eventos/${event.id}?section=editor`}>Continuar en el editor manual →</Link></section>;
}
