'use client';
import {useRef,useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {Button,Field,Notice} from '@/components/tc/ui';
import Review from '@/components/ai/Review';
import {featureNames,type Feature,type Proposal,type ProviderStatus} from '@/lib/ai/model';
import type {EventRecord} from '@/lib/organizer/model';
export default function AI({event,status,initialFeature='event',only}:{event:EventRecord;status:ProviderStatus;initialFeature?:Feature;only?:Feature[]}){
 const router=useRouter(),heading=useRef<HTMLDivElement>(null),[feature,setFeature]=useState<Feature>(initialFeature),[prompt,setPrompt]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[proposal,setProposal]=useState<Proposal|null>(null);
 const available=only||(['event','title','description','shorten','summary','faq','seo','tiers','readiness','promotion'] as Feature[]);
 async function request(body:object){const r=await fetch(`/api/organizer/events/${event.id}/ai`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw new Error(d.error||'No pudimos completar la solicitud.');return d;}
 async function propose(){setBusy(true);setMessage('');try{setProposal(await request({action:'generate',prompt:prompt.trim()||`Prepara una propuesta para la tarea: ${featureNames[feature]}. Usa solamente los datos disponibles.`,feature,requestId:crypto.randomUUID()}));setTimeout(()=>heading.current?.querySelector<HTMLElement>('h2')?.focus(),0);}catch(e){setMessage(e instanceof Error?e.message:'No hay conexión. Tu texto se conserva.');}finally{setBusy(false);}}
 async function apply(patch:Record<string,unknown>,confirmed:boolean){setBusy(true);setMessage('');try{await request({action:'apply',proposalId:proposal?.id,patch,confirmed});setProposal(null);setMessage('Campos seleccionados guardados. Puedes revisarlos y volver a editarlos.');router.refresh();}catch(e){setMessage(e instanceof Error?e.message:'No se pudo guardar.');}finally{setBusy(false);}}
 async function reject(){setBusy(true);try{await request({action:'reject',proposalId:proposal?.id});setProposal(null);setMessage('Propuesta rechazada. El evento no cambió.');}catch(e){setMessage(e instanceof Error?e.message:'No se pudo rechazar.');}finally{setBusy(false);}}
 return <section className="panel stack" aria-busy={busy}><p className="eyebrow">TicketChile AI / {event.title||'Este evento'}</p><h2>Una propuesta para esta tarea.</h2><Notice>{status.label}</Notice><Field label="Tarea contextual"><select value={feature} onChange={e=>{setFeature(e.target.value as Feature);setProposal(null);}}>{available.map(f=><option key={f} value={f}>{featureNames[f]}</option>)}</select></Field><Field label="Instrucciones para la propuesta" hint="No incluyas datos personales. Se envían solo campos necesarios de este evento o métricas agregadas."><textarea rows={4} maxLength={4000} value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Qué quieres mejorar y qué datos ya tienes confirmados…"/></Field><Button disabled={busy||!status.enabled} onClick={()=>void propose()}>{busy?'Preparando propuesta…':'Generar propuesta'}</Button><div role="status" aria-live="polite">{busy?'Generando y validando. Tu evento sigue intacto.':message}</div>{proposal&&<div ref={heading}><Review key={proposal.id} proposal={proposal} current={event} busy={busy} onApply={apply} onReject={()=>void reject()}/></div>}{event.capabilities.includes('event.edit')&&<Link href={`/organizador/eventos/${event.id}?section=editor`}>Continuar en el editor manual →</Link>}</section>;
}
