'use client';
import { useCallback,useEffect,useRef,useState } from 'react';
import { Button,Field,Notice } from '@/components/tc/ui';
import Media from '@/components/tc/Media';
import { emptyDraft,type Draft,type EventRecord } from '@/lib/organizer/model';
const sections=['Información','Fecha y lugar','Imagen','Entradas','Información adicional'];
function localDate(value:string|null){if(!value)return '';const d=new Date(value);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);}
export default function Editor({event,initialSection=0}:{event:EventRecord;initialSection?:number}){
  const initial=Object.fromEntries(Object.keys(emptyDraft).map(k=>[k,event[k as keyof Draft]])) as Draft;
  const [draft,setDraft]=useState(initial),[tab,setTab]=useState(initialSection),[status,setStatus]=useState('Guardado'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[conflict,setConflict]=useState(false),[confirmPrice,setConfirmPrice]=useState(false);
  const revision=useRef(event.revision),saved=useRef(JSON.stringify(initial)),latest=useRef(draft),inflight=useRef(false);
  latest.current=draft;
  const priceChanged=event.tiers.some(t=>(t.sold||0)>0)&&draft.tiers.some(t=>{const old=(JSON.parse(saved.current) as Draft).tiers.find(o=>o.id===t.id);return old&&old.price_clp!==t.price_clp;});
  const dirty=JSON.stringify(draft)!==saved.current;
  const save=useCallback(async(confirm=false)=>{
    if(inflight.current||conflict)return;
    const snapshot=latest.current,serialized=JSON.stringify(snapshot);if(serialized===saved.current)return;
    inflight.current=true;setBusy(true);setStatus('Guardando…');setError('');
    try{const r=await fetch(`/api/organizer/events/${event.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:revision.current,draft:snapshot,confirmPrices:confirm})});const d=await r.json();if(!r.ok){if(d.code==='REVISION_CONFLICT')setConflict(true);throw new Error(d.error);}
      revision.current=d.revision;saved.current=serialized;setStatus('Guardado');setConfirmPrice(false);
    }catch(e){setStatus('Sin guardar');setError(e instanceof Error?e.message:'Error de conexión. Reintenta.');}finally{inflight.current=false;setBusy(false);}
  },[event.id,conflict]);
  useEffect(()=>{if(!dirty||busy||conflict||priceChanged||error)return;const timer=setTimeout(()=>void save(),1500);return()=>clearTimeout(timer);},[draft,dirty,busy,conflict,priceChanged,error,save]);
  useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(JSON.stringify(latest.current)!==saved.current){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[]);
  useEffect(()=>{const guard=(e:MouseEvent)=>{const a=(e.target as Element).closest('a');if(a&&JSON.stringify(latest.current)!==saved.current&&!window.confirm('Tienes cambios sin guardar. ¿Descartarlos y salir del editor?')){e.preventDefault();e.stopPropagation();}};document.addEventListener('click',guard,true);return()=>document.removeEventListener('click',guard,true);},[]);
  function change<K extends keyof Draft>(key:K,value:Draft[K]){setDraft(d=>({...d,[key]:value}));setError('');setStatus('Cambios pendientes');}
  function field(key: keyof Draft,label:string,textarea=false){return <Field key={key} label={label}>{textarea?<textarea rows={5} value={String(draft[key]||'')} onChange={e=>change(key,e.target.value as never)}/>:<input value={String(draft[key]||'')} onChange={e=>change(key,e.target.value as never)}/>}</Field>;}
  function tier(index:number,key:string,value:unknown){change('tiers',draft.tiers.map((t,i)=>i===index?{...t,[key]:value}:t));}
  async function upload(key:'image'|'hero_desktop'|'hero_mobile',file?:File){if(!file)return;setBusy(true);setError('');try{const r=await fetch(`/api/media?eventId=${event.id}`,{method:'POST',headers:{'Content-Type':file.type},body:file});const d=await r.json();if(!r.ok)throw new Error(d.error);change(key,d.url);}catch(e){setError(e instanceof Error?e.message:'No se pudo cargar la imagen.');}finally{setBusy(false);}}
  return <div className="stack"><div className="row between"><div><p className="eyebrow">Editor del evento</p><p aria-live="polite" className="hint">{status} · Versión {revision.current}</p></div><Button variant="secondary" disabled={!dirty||busy||conflict||(priceChanged&&!confirmPrice)} onClick={()=>void save(confirmPrice)}>Guardar ahora</Button></div><nav className="tabs org-editor-tabs" aria-label="Secciones del editor">{sections.map((s,i)=><button type="button" aria-current={tab===i?'step':undefined} key={s} onClick={()=>setTab(i)}>{String(i+1).padStart(2,'0')} / {s}</button>)}</nav>
    {error&&<Notice error>{error} {conflict?<button className="btn secondary" onClick={()=>{if(window.confirm('Se descartarán los cambios locales para cargar la versión actual.'))window.location.reload();}}>Cargar versión actual</button>:<Button variant="secondary" disabled={busy||(priceChanged&&!confirmPrice)} onClick={()=>void save(confirmPrice)}>Reintentar</Button>}</Notice>}
    {priceChanged&&<Notice>Los nuevos precios solo afectan compras futuras. Las reservas y compras anteriores conservan su importe.<Field label="Confirmo el cambio de precio"><input type="checkbox" checked={confirmPrice} onChange={e=>setConfirmPrice(e.target.checked)}/></Field></Notice>}
    <section className="panel stack"><h2>{sections[tab]}</h2>{tab===0&&<>{field('title','Nombre del evento')}<Field label="Categoría"><select value={draft.category_slug} onChange={e=>change('category_slug',e.target.value)}><option value="">Selecciona una categoría</option>{['conciertos','fiestas','festivales','deportes','teatro','stand-up','familiar'].map(c=><option key={c}>{c}</option>)}</select></Field>{field('description','Descripción',true)}<Field label="Visibilidad"><select value={draft.visibility} onChange={e=>change('visibility',e.target.value as Draft['visibility'])}><option value="PUBLIC">Público en cartelera</option><option value="UNLISTED">Solo mediante enlace</option></select></Field></>}
    {tab===1&&<><Notice>Los horarios del selector usan la zona de este dispositivo. Se guardan como instantes absolutos; la zona del evento identifica el horario oficial.</Notice><div className="org-two">{(['date_iso','end_at'] as const).map((k,i)=><Field key={k} label={i?'Término (hora de este dispositivo)':'Inicio (hora de este dispositivo)'}><input type="datetime-local" value={localDate(draft[k])} onChange={e=>change(k,e.target.value?new Date(e.target.value).toISOString():null)}/></Field>)}</div>{field('timezone','Zona horaria IANA del evento')}{field('venue','Recinto')}{field('address','Dirección exacta')}<div className="org-two">{field('city','Ciudad')}{field('region','Región')}</div></>}
    {tab===2&&<><p className="muted">PNG, JPEG o WebP, hasta 5 MB. La carga valida, normaliza y elimina metadatos.</p>{(['image','hero_desktop','hero_mobile'] as const).map((k,i)=><div className="org-media-row" key={k}><div className="org-media"><Media src={draft[k]} alt={['Imagen principal','Portada escritorio','Portada móvil'][i]} sizes="240px"/></div><Field label={['Imagen principal','Portada escritorio (opcional)','Portada móvil (opcional)'][i]}><input type="file" accept="image/png,image/jpeg,image/webp" disabled={busy} onChange={e=>void upload(k,e.target.files?.[0])}/></Field></div>)}</>}
    {tab===3&&<><Field label="Aforo total confirmado"><input type="number" min={0} max={1000000} value={draft.capacity} onChange={e=>change('capacity',Number(e.target.value))}/></Field><p className="hint">Asignado: {draft.tiers.reduce((n,t)=>n+t.capacity,0)} / {draft.capacity}. No reduzcas stock por debajo de vendido + reservado.</p>{draft.tiers.map((t,i)=><fieldset className="org-tier stack" key={t.id}><legend>{t.name||`Entrada ${i+1}`}</legend><div className="org-two"><Field label="Nombre del tipo"><input value={t.name} onChange={e=>tier(i,'name',e.target.value)}/></Field><Field label="Descripción"><input value={t.description} onChange={e=>tier(i,'description',e.target.value)}/></Field></div><div className="org-three">{(['price_clp','capacity','max_per_order'] as const).map((k,j)=><Field key={k} label={['Precio CLP','Stock total','Máximo por compra'][j]}><input type="number" min={k==='max_per_order'?1:0} max={k==='max_per_order'?10:100000000} value={t[k]} onChange={e=>tier(i,k,Number(e.target.value))}/></Field>)}</div><div className="org-two">{(['sales_start','sales_end'] as const).map((k,j)=><Field key={k} label={j?'Fin de venta (hora local del dispositivo)':'Inicio de venta (hora local del dispositivo)'}><input type="datetime-local" value={localDate(t[k])} onChange={e=>tier(i,k,e.target.value?new Date(e.target.value).toISOString():null)}/></Field>)}</div><div className="row"><Field label="Visible al comprador"><input type="checkbox" checked={t.visible} onChange={e=>tier(i,'visible',e.target.checked)}/></Field><Field label="Venta activa"><input type="checkbox" checked={t.active} onChange={e=>tier(i,'active',e.target.checked)}/></Field></div><p className="hint">{t.sold||0} vendidas · {t.held||0} reservadas. Desactiva un tipo para conservar su historial. Precio cero requiere el flujo de cortesías de M8.</p></fieldset>)}<Button variant="secondary" disabled={draft.tiers.length>=50} onClick={()=>change('tiers',[...draft.tiers,{id:`tier_${crypto.randomUUID()}`,name:'Nueva entrada',description:'',price_clp:0,capacity:0,max_per_order:4,sales_start:null,sales_end:null,visible:true,active:false}])}>Añadir tipo de entrada +</Button></>}
    {tab===4&&<>{field('age_policy','Condición de edad confirmada')}{field('access_info','Información de acceso y accesibilidad',true)}{field('faq','Preguntas frecuentes e información adicional',true)}<p className="hint">No incluyas condiciones legales o de devolución sin aprobación.</p></>}
    </section><div className="row between"><Button variant="quiet" disabled={tab===0} onClick={()=>setTab(t=>t-1)}>← Anterior</Button><Button variant="secondary" disabled={tab===sections.length-1} onClick={()=>setTab(t=>t+1)}>Siguiente →</Button></div><p className="hint">El guardado automático no publica. Espera “Guardado” antes de cambiar de pantalla.</p></div>;
}
