'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import {Button,Field,Notice} from '@/components/tc/ui';
import {transitions,stateNames,type EventRecord,type Lifecycle as State} from '@/lib/organizer/model';
export default function Lifecycle({event}:{event:EventRecord}){
 const [target,setTarget]=useState<State|null>(null),[confirmation,setConfirmation]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);const router=useRouter();
 async function execute(){setBusy(true);setError('');try{const r=await fetch(`/api/organizer/events/${event.id}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:event.revision,target,confirmation})});const d=await r.json();if(!r.ok)throw new Error(d.error);setTarget(null);setConfirmation('');router.refresh();}catch(e){setError(e instanceof Error?e.message:'No se pudo cambiar el estado.');}finally{setBusy(false);}}
 return <div className="stack"><div className="row">{transitions[event.lifecycle].map(s=><Button key={s} variant={s==='PUBLISHED'?'primary':'secondary'} onClick={()=>{setTarget(s);setConfirmation('');}}>{s==='IN_REVIEW'?'Revisar para publicación':stateNames[s]}</Button>)}</div>{target&&<section className="panel stack"><h3>Confirmar: {stateNames[target]}</h3><p className="muted">{target==='CANCELLED'?'Esta acción cierra las ventas, libera reservas e invalida entradas sin usar. Reembolsos y comunicaciones quedan pendientes de revisión operativa; no se ejecutan automáticamente.':target==='PAUSED'?'El evento sale de cartelera y no acepta nuevas compras. Las reservas ya creadas pueden finalizar; las entradas existentes siguen vigentes.':target==='PUBLISHED'?'El evento estará accesible y sus entradas activas podrán venderse según sus ventanas. Revisa el checklist antes de confirmar.':'El cambio quedará registrado en la auditoría.'}</p><Field label={`Escribe ${target==='CANCELLED'?`CANCELAR ${event.id}`:target}`}><input value={confirmation} onChange={e=>setConfirmation(e.target.value)} autoComplete="off"/></Field><div className="row"><Button disabled={busy||confirmation!==(target==='CANCELLED'?`CANCELAR ${event.id}`:target)} onClick={()=>void execute()}>Confirmar cambio</Button><Button variant="quiet" onClick={()=>setTarget(null)}>Volver</Button></div></section>}{error&&<Notice error>{error}</Notice>}</div>;
}
