'use client';
import {capabilityNames,roleNames} from '@/lib/organizer/model';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import {Button,Field,Notice} from '@/components/tc/ui';
import type {StaffEntry} from '@/lib/organizer/operations.server';
const roles={ORGANIZER_MANAGER:['event.read','event.edit','scanner.read','scanner.checkin','attendees.read','attendees.export'],ORGANIZER_DOOR:['scanner.read','scanner.checkin'],ORGANIZER_FINANCE:['finance.read'],ORGANIZER_SUPPORT:['attendees.read']};
type Role=keyof typeof roles;
export default function Staff({organizerId,eventId,staff,invites}:{organizerId:string;eventId:string;staff:StaffEntry[];invites:StaffEntry[]}){
 const router=useRouter(),[email,setEmail]=useState(''),[role,setRole]=useState<Role>('ORGANIZER_DOOR'),[caps,setCaps]=useState<string[]>(roles.ORGANIZER_DOOR),[editing,setEditing]=useState<StaffEntry|null>(null),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function action(operation:string,body:Record<string,unknown>){setBusy(true);setError('');setMessage('');try{const r=await fetch(`/api/security/${operation}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({organizerId,...body})});const d=await r.json();if(!r.ok)throw new Error(d.error);setMessage(operation==='invite'?'Invitación guardada y en cola de entrega.':'Acceso actualizado.');setEditing(null);router.refresh();}catch(e){setError(e instanceof Error?e.message:'No se pudo actualizar.');}finally{setBusy(false);}}
 return <div className="stack"><Notice>Solo el propietario administra permisos. Las nuevas invitaciones se limitan a este evento.</Notice><section className="panel stack"><h2>{editing?'Editar permisos':'Invitar al equipo'}</h2>{editing?<p>{editing.email} · {editing.event_ids?'Eventos asignados conservados':'Acceso a toda la organización'}</p>:<Field label="Email de la cuenta"><input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></Field>}<Field label="Rol"><select value={role} onChange={e=>{const r=e.target.value as Role;setRole(r);setCaps(roles[r]);}}>{Object.keys(roles).map(r=><option key={r} value={r}>{roleNames[r]}</option>)}</select></Field><fieldset className="stack-sm"><legend>Permisos explícitos</legend>{roles[role].map(c=><Field label={capabilityNames[c]} key={c}><input type="checkbox" checked={caps.includes(c)} onChange={e=>setCaps(e.target.checked?[...caps,c]:caps.filter(x=>x!==c))}/></Field>)}</fieldset><Button disabled={busy||!caps.length||(!editing&&!email)} onClick={()=>void action(editing?'staff-update':'invite',{email,role,capabilities:caps,eventIds:editing?editing.event_ids:[eventId],...(editing?{id:editing.id}:{})})}>{editing?'Confirmar permisos':'Enviar invitación'}</Button>{editing&&<Button variant="quiet" onClick={()=>setEditing(null)}>Volver</Button>}</section>{message&&<Notice>{message}</Notice>}{error&&<Notice error>{error}</Notice>}<h2>Equipo actual</h2>{!staff.length&&<p className="muted">No hay miembros adicionales asignados.</p>}{staff.map(s=><div className="history-row" key={s.id}><div><h3>{s.email}</h3><p className="hint">{roleNames[s.role]} · {s.event_ids?'Eventos específicos':'Toda la organización'}</p><p className="hint">{s.capabilities.join(' · ')}</p></div><div className="row"><Button variant="quiet" onClick={()=>{setEditing(s);setRole(s.role as Role);setCaps(s.capabilities);}}>Permisos</Button><Button variant="secondary" disabled={busy} onClick={()=>{if(window.confirm(`Revocar la membresía de ${s.email} en esta organización, incluidos sus otros eventos asignados?`))void action('staff-revoke',{id:s.id});}}>Revocar</Button></div></div>)}<h2>Invitaciones pendientes</h2>{!invites.length&&<p className="muted">No hay invitaciones pendientes.</p>}{invites.map(s=><div className="history-row" key={s.id}><div>{s.email}<p className="hint">{roleNames[s.role]} · Pendiente de aceptación</p></div><Button variant="quiet" disabled={busy} onClick={()=>void action('invite-revoke',{id:s.id})}>Revocar invitación</Button></div>)}</div>;
}
